# Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build arguments for environment variables
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_FUNCTIONS_URL
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_STRIPE_PRICE_MONTHLY_STARTER
ARG VITE_STRIPE_PRODUCT_KEY_STARTER
ARG VITE_STRIPE_PRICE_MONTHLY_STANDARD
ARG VITE_STRIPE_PRODUCT_KEY_STANDARD
ARG VITE_STRIPE_PRICE_MONTHLY_PREMIUM
ARG VITE_STRIPE_PRODUCT_KEY_PREMIUM
ARG VITE_BRIDGE_CLIENT_ID
ARG VITE_BRIDGE_CLIENT_SECRET
ARG VITE_BRIDGE_BASE_URL
ARG VITE_BRIDGE_ENV

# Set as environment variables for the build
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_FUNCTIONS_URL=$VITE_SUPABASE_FUNCTIONS_URL
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_STRIPE_PRICE_MONTHLY_STARTER=$VITE_STRIPE_PRICE_MONTHLY_STARTER
ENV VITE_STRIPE_PRODUCT_KEY_STARTER=$VITE_STRIPE_PRODUCT_KEY_STARTER
ENV VITE_STRIPE_PRICE_MONTHLY_STANDARD=$VITE_STRIPE_PRICE_MONTHLY_STANDARD
ENV VITE_STRIPE_PRODUCT_KEY_STANDARD=$VITE_STRIPE_PRODUCT_KEY_STANDARD
ENV VITE_STRIPE_PRICE_MONTHLY_PREMIUM=$VITE_STRIPE_PRICE_MONTHLY_PREMIUM
ENV VITE_STRIPE_PRODUCT_KEY_PREMIUM=$VITE_STRIPE_PRODUCT_KEY_PREMIUM
ENV VITE_BRIDGE_CLIENT_ID=$VITE_BRIDGE_CLIENT_ID
ENV VITE_BRIDGE_CLIENT_SECRET=$VITE_BRIDGE_CLIENT_SECRET
ENV VITE_BRIDGE_BASE_URL=$VITE_BRIDGE_BASE_URL
ENV VITE_BRIDGE_ENV=$VITE_BRIDGE_ENV

# Build the application
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built assets from build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
