version: '3.8'

services:
  bailogenius-front:
    image: bailogenius-front:latest
    container_name: bailogenius-front
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - bailogenius-network

networks:
  bailogenius-network:
    driver: bridge
